{
    "__comment__" : "original spec: https://github.com/vulnerable-apps/crAPI/blob/develop/openapi-spec/openapi-spec.json",
    "openapi" : "3.0.1",
    "info" : {
      "title" : "OWASP crAPI API (python service)",
      "version" : "1-oas3"
    },
    "externalDocs" : {
      "description" : "Completely Ridiculous API (crAPI). Python part",
      "url" : "https://github.com/OWASP/crAPI"
    },
    "servers" : [ {
      "url" : "http://localhost:8888"
    } ],
    "paths": {
      "/workshop/api/shop/products" : {
        "parameters" : [ ],
        "get" : {
          "operationId" : "get_products",
          "summary" : "Get Products",
          "description" : "Used to get products for the shop",
          "tags" : [ "Workshop / Shop" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "responses" : {
            "200" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "credit", "products" ],
                    "properties" : {
                      "credit" : {
                        "type" : "number"
                      },
                      "products" : {
                        "$ref" : "#/components/schemas/Product"
                      }
                    }
                  }
                }
              },
              "description" : "OK"
            }
          }
        },
        "post" : {
          "operationId" : "add_new_product",
          "summary" : "Add A New Product",
          "description" : "Used to add the specified product to the product catalog.",
          "tags" : [ "Workshop / Shop" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "requestBody" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/NewProduct"
                }
              }
            },
            "required" : true
          },
          "responses" : {
            "200" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "$ref" : "#/components/schemas/Product"
                  }
                }
              },
              "description" : "OK"
            },
            "400" : {
              "description" : "Bad Request!",
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "additionalProperties" : true
                  }
                }
              }
            }
          }
        }
      },
      "/workshop/api/shop/orders" : {
        "post" : {
          "operationId" : "create_order",
          "summary" : "Create Order",
          "description" : "Used to create a new order for a product in the shop.",
          "tags" : [ "Workshop / Shop" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "requestBody" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ProductQuantity"
                }
              }
            },
            "required" : true
          },
          "responses" : {
            "200" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "id", "message", "credit" ],
                    "properties" : {
                      "id" : {
                        "type" : "integer"
                      },
                      "message" : {
                        "type" : "string"
                      },
                      "credit" : {
                        "type" : "number",
                        "format" : "float"
                      }
                    }
                  }
                }
              },
              "description" : "OK"
            },
            "400" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    },
                    "example" : {
                      "message" : "Insufficient Balance. Please apply coupons to get more\nbalance!"
                    }
                  }
                }
              },
              "description" : "Bad Request!"
            }
          }
        }
      },
      "/workshop/api/shop/orders/{order_id}" : {
        "put" : {
          "operationId" : "update_order",
          "summary" : "Update Order",
          "description" : "Used to update the order specified by the order_id.",
          "tags" : [ "Workshop / Shop" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "parameters" : [ {
            "in" : "path",
            "name" : "order_id",
            "schema" : {
              "type" : "integer"
            },
            "required" : true
          } ],
          "requestBody" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/ProductQuantity"
                }
              }
            },
            "required" : true
          },
          "responses" : {
            "200" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "orders" ],
                    "properties" : {
                      "orders" : {
                        "$ref" : "#/components/schemas/Order"
                      }
                    }
                  }
                }
              },
              "description" : "OK"
            },
            "400" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    },
                    "example" : {
                      "message" : "The value of 'status' has to be 'delivered', 'return pending' or 'returned'"
                    }
                  }
                }
              },
              "description" : "Bad Request!"
            },
            "403" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    },
                    "example" : {
                      "message" : "You are not allowed to access this resource!'"
                    }
                  }
                }
              },
              "description" : "Forbidden!"
            }
          }
        },
        "get" : {
          "operationId" : "get_order_byID",
          "summary" : "Get Order Based on ID",
          "description" : "Used to get the order details for order identified by order_id.",
          "tags" : [ "Workshop / Shop" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "parameters" : [ {
            "in" : "path",
            "name" : "order_id",
            "schema" : {
              "type" : "integer"
            },
            "required" : true
          } ],
          "responses" : {
            "200" : {
              "description" : "OK",
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "orders" ],
                    "properties" : {
                      "orders" : {
                        "$ref" : "#/components/schemas/Order"
                      }
                    }
                  }
                }
              }
            },
            "403" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    },
                    "example" : {
                      "message" : "You are not allowed to access this resource!'"
                    }
                  }
                }
              },
              "description" : "Forbidden!"
            }
          }
        }
      },
      "/workshop/api/shop/orders/all" : {
        "get" : {
          "operationId" : "get_orders",
          "summary" : "Get Orders",
          "description" : "Used to get user's past orders",
          "tags" : [ "Workshop / Shop" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "responses" : {
            "200" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "orders" ],
                    "properties" : {
                      "orders" : {
                        "type" : "array",
                        "items" : {
                          "type" : "object",
                          "required" : [ "created_on", "id", "product", "quantity", "status", "user" ],
                          "properties" : {
                            "quantity" : {
                              "type" : "number"
                            },
                            "id" : {
                              "type" : "number"
                            },
                            "status" : {
                              "type" : "string"
                            },
                            "created_on" : {
                              "type" : "string"
                            },
                            "user" : {
                              "type" : "object",
                              "required" : [ "email", "number" ],
                              "properties" : {
                                "email" : {
                                  "type" : "string"
                                },
                                "number" : {
                                  "type" : "string"
                                }
                              }
                            },
                            "product" : {
                              "type" : "object",
                              "required" : [ "id", "image_url", "name", "price" ],
                              "properties" : {
                                "id" : {
                                  "type" : "number"
                                },
                                "image_url" : {
                                  "type" : "string"
                                },
                                "name" : {
                                  "type" : "string"
                                },
                                "price" : {
                                  "type" : "string"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              },
              "description" : ""
            }
          }
        },
        "parameters" : [ ]
      },
      "/workshop/api/shop/orders/return_order" : {
        "post" : {
          "operationId" : "return_order",
          "summary" : "Return Order",
          "description" : "Used to return order specified by the order_id",
          "tags" : [ "Workshop / Shop" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "parameters" : [ {
            "in" : "query",
            "name" : "order_id",
            "schema" : {
              "type" : "integer",
              "example": 33
            },
            "required" : true
          } ],
          "responses" : {
            "200" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message", "order", "qr_code_url" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      },
                      "order" : {
                        "$ref" : "#/components/schemas/Order"
                      },
                      "qr_code_url" : {
                        "type" : "string",
                        "format" : "url"
                      }
                    }
                  }
                }
              },
              "description" : "OK"
            },
            "400" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    },
                    "example" : {
                      "message" : "This order has already been returned!"
                    }
                  }
                }
              },
              "description" : "Bad Request!"
            },
            "403" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    },
                    "example" : {
                      "message" : "You are not allowed to access this resource!'"
                    }
                  }
                }
              },
              "description" : "Forbidden!"
            }
          }
        }
      },
      "/workshop/api/shop/apply_coupon" : {
        "post" : {
          "operationId" : "apply_coupon",
          "summary" : "Apply Coupon",
          "description" : "Used to apply the coupon for the current user.",
          "tags" : [ "Workshop / Shop" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "requestBody" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "required" : [ "amount", "coupon_code" ],
                  "properties" : {
                    "amount" : {
                      "type" : "number",
                      "example": 75
                    },
                    "coupon_code" : {
                      "type" : "string",
                      "example": "TRAC075"
                    }
                  }
                }
              }
            }
          },
          "responses" : {
            "200" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "credit", "message" ],
                    "properties" : {
                      "credit" : {
                        "type" : "number"
                      },
                      "message" : {
                        "type" : "string"
                      }
                    }
                  }
                }
              },
              "description" : ""
            },
            "400" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    }
                  }
                }
              },
              "description" : ""
            }
          }
        },
        "parameters" : [ ]
      },
      "/workshop/api/shop/return_qr_code" : {
        "get" : {
          "operationId" : "get_workshop_qr_code",
          "summary" : "Get Workshop",
          "description" : "Used to get the return qr code image for UPS shipments.",
          "tags" : [ "Workshop / Shop" ],
          "security" : [ { } ],
          "parameters" : [ {
            "name" : "Accept",
            "in" : "header",
            "description" : "The server doesn't like image/png in accept!",
            "required" : true,
            "style" : "simple",
            "schema" : {
              "type" : "string",
              "example" : "*/*"
            }
          } ],
          "responses" : {
            "200" : {
              "content" : {
                "" : {
                  "schema" : {
                    "type" : "string",
                    "format" : "binary"
                  }
                }
              },
              "description" : "QR Code PNG Image"
            }
          }
        }
      },
      "/workshop/api/mechanic/" : {
        "get" : {
          "operationId" : "get_mechanics",
          "summary" : "Get Mechanics",
          "description" : "Used to get all the available mechanics",
          "tags" : [ "Workshop / Mechanic" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "responses" : {
            "200" : {
              "description" : "OK",
              "headers" : {
                "Transfer-Encoding" : {
                  "content" : {
                    "text/plain" : {
                      "schema" : {
                        "type" : "string"
                      },
                      "example" : "chunked"
                    }
                  }
                }
              },
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "mechanics" ],
                    "properties" : {
                      "mechanics" : {
                        "type" : "array",
                        "items" : {
                          "type" : "object",
                          "required" : [ "id", "mechanic_code", "user" ],
                          "properties" : {
                            "id" : {
                              "type" : "number"
                            },
                            "mechanic_code" : {
                              "type" : "string"
                            },
                            "user" : {
                              "type" : "object",
                              "required" : [ "email", "number" ],
                              "properties" : {
                                "email" : {
                                  "type" : "string"
                                },
                                "number" : {
                                  "type" : "string"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  },
                  "example" : {
                    "mechanics" : [ {
                      "id" : 1,
                      "mechanic_code" : "TRAC_MECH1",
                      "user" : {
                        "email" : "mechanic.one@example.com",
                        "number" : ""
                      }
                    }, {
                      "id" : 2,
                      "mechanic_code" : "TRAC_MECH2",
                      "user" : {
                        "email" : "mechanic.two@example.com",
                        "number" : ""
                      }
                    } ]
                  }
                }
              }
            }
          }
        },
        "parameters" : [ ]
      },
      "/workshop/api/merchant/contact_mechanic" : {
        "post" : {
          "operationId" : "contact_mechanic",
          "summary" : "Contact Mechanic",
          "description" : "Used to contact a mechanic for a service request on your vehicle",
          "tags" : [ "Workshop / Mechanic" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "requestBody" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "required" : [ "mechanic_api", "mechanic_code", "number_of_repeats", "problem_details", "repeat_request_if_failed", "vin" ],
                  "properties" : {
                    "number_of_repeats" : {
                      "type" : "number"
                    },
                    "mechanic_api" : {
                      "type" : "string"
                    },
                    "vin" : {
                      "type" : "string"
                    },
                    "repeat_request_if_failed" : {
                      "type" : "boolean"
                    },
                    "problem_details" : {
                      "type" : "string"
                    },
                    "mechanic_code" : {
                      "type" : "string"
                    }
                  }
                },
                "example" : {
                  "mechanic_api" : "http://localhost:8000/workshop/api/mechanic/receive_report",
                  "mechanic_code" : "TRAC_JHN",
                  "number_of_repeats" : 1,
                  "repeat_request_if_failed" : false,
                  "problem_details" : "Hi Jhon",
                  "vin" : "8UOLV89RGKL908077"
                }
              }
            }
          },
          "responses" : {
            "200" : {
              "description" : "OK",
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "response_from_mechanic_api", "status" ],
                    "properties" : {
                      "response_from_mechanic_api" : {
                        "type" : "object",
                        "required" : [ "id", "sent", "report_link" ],
                        "properties" : {
                          "id" : {
                            "type" : "integer",
                            "format" : "int32"
                          },
                          "sent" : {
                            "type" : "boolean"
                          },
                          "report_link" : {
                            "type" : "string"
                          }
                        }
                      },
                      "status" : {
                        "type" : "integer",
                        "format" : "int32"
                      }
                    }
                  },
                  "example" : {
                    "response_from_mechanic_api" : {
                      "id" : 17,
                      "sent" : true,
                      "report_link" : "http://localhost:8888/workshop/api/mechanic/mechanic_report?report_id=17"
                    },
                    "status" : 200
                  }
                }
              }
            },
            "400" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    }
                  }
                }
              },
              "description" : "Bad Request!"
            },
            "503" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    }
                  }
                }
              },
              "description" : "Service Unavailable"
            }
          }
        },
        "parameters" : [ ]
      },
      "/workshop/api/mechanic/receive_report" : {
        "get" : {
          "operationId" : "create_service_report",
          "summary" : "Create and Assign a Service Report",
          "description" : "Used to create the service report and assign to the mechanic",
          "tags" : [ "Workshop / Mechanic" ],
          "security" : [ ],
          "parameters" : [ {
            "name" : "mechanic_code",
            "in" : "query",
            "required" : true,
            "schema" : {
              "type" : "string",
              "example" : "TRAC_MECH1"
            }
          }, {
            "name" : "problem_details",
            "in" : "query",
            "required" : true,
            "schema" : {
              "type" : "string",
              "example" : "My car has engine trouble, and I need urgent help!"
            }
          }, {
            "name" : "vin",
            "in" : "query",
            "required" : true,
            "schema" : {
              "type" : "string",
              "example" : "0BZCX25UTBJ987271"
            }
          } ],
          "responses" : {
            "200" : {
              "description" : "OK",
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "id", "sent", "report_link" ],
                    "properties" : {
                      "id" : {
                        "type" : "integer"
                      },
                      "sent" : {
                        "type" : "string"
                      },
                      "report_link" : {
                        "type" : "string",
                        "format" : "url"
                      }
                    }
                  }
                }
              }
            },
            "400" : {
              "description" : "Bad Request!",
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "additionalProperties" : true
                  }
                }
              }
            }
          }
        }
      },
      "/workshop/api/mechanic/mechanic_report" : {
        "get" : {
          "operationId" : "get_report_byID",
          "summary" : "Get Service Report",
          "description" : "Used to get the service report specified by the report_id",
          "tags" : [ "Workshop / Mechanic" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "parameters" : [ {
            "name" : "report_id",
            "in" : "query",
            "description" : "",
            "required" : true,
            "style" : "form",
            "explode" : true,
            "schema" : {
              "type" : "integer",
              "format" : "int32",
              "example" : 2
            }
          } ],
          "responses" : {
            "200" : {
              "description" : "OK",
              "headers" : {
                "Server" : {
                  "content" : {
                    "text/plain" : {
                      "schema" : {
                        "type" : "string"
                      },
                      "example" : "openresty/1.17.8.2"
                    }
                  }
                },
                "Date" : {
                  "content" : {
                    "text/plain" : {
                      "schema" : {
                        "type" : "string"
                      },
                      "example" : "Tue, 21 Sep 2021 22:33:37 GMT"
                    }
                  }
                },
                "Transfer-Encoding" : {
                  "content" : {
                    "text/plain" : {
                      "schema" : {
                        "type" : "string"
                      },
                      "example" : "chunked"
                    }
                  }
                },
                "Allow" : {
                  "content" : {
                    "text/plain" : {
                      "schema" : {
                        "type" : "string"
                      },
                      "example" : "GET, HEAD, OPTIONS"
                    }
                  }
                },
                "Vary" : {
                  "content" : {
                    "text/plain" : {
                      "schema" : {
                        "type" : "string"
                      },
                      "example" : "Origin, Cookie"
                    }
                  }
                },
                "X-Frame-Options" : {
                  "content" : {
                    "text/plain" : {
                      "schema" : {
                        "type" : "string"
                      },
                      "example" : "SAMEORIGIN"
                    }
                  }
                }
              },
              "content" : {
                "application/json" : {
                  "schema" : {
                    "title" : "Service Request",
                    "required" : [ "id", "mechanic", "vehicle", "problem_details", "status", "created_on" ],
                    "type" : "object",
                    "properties" : {
                      "id" : {
                        "type" : "integer",
                        "format" : "int32"
                      },
                      "mechanic" : {
                        "title" : "Mechanic",
                        "required" : [ "id", "mechanic_code", "user" ],
                        "type" : "object",
                        "properties" : {
                          "id" : {
                            "type" : "integer",
                            "format" : "int32"
                          },
                          "mechanic_code" : {
                            "type" : "string"
                          },
                          "user" : {
                            "title" : "user",
                            "required" : [ "email", "number" ],
                            "type" : "object",
                            "properties" : {
                              "email" : {
                                "type" : "string"
                              },
                              "number" : {
                                "type" : "string"
                              }
                            }
                          }
                        },
                        "example" : {
                          "id" : 1,
                          "mechanic_code" : "TRAC_MECH1",
                          "user" : {
                            "email" : "mechanic.one@example.com",
                            "number" : "415-654-3212"
                          }
                        }
                      },
                      "vehicle" : {
                        "title" : "vehicle",
                        "required" : [ "id", "vin", "owner" ],
                        "type" : "object",
                        "properties" : {
                          "id" : {
                            "type" : "integer",
                            "format" : "int32"
                          },
                          "vin" : {
                            "type" : "string"
                          },
                          "owner" : {
                            "title" : "owner",
                            "required" : [ "email", "number" ],
                            "type" : "object",
                            "properties" : {
                              "email" : {
                                "type" : "string"
                              },
                              "number" : {
                                "type" : "string"
                              }
                            }
                          }
                        },
                        "example" : {
                          "id" : 23,
                          "vin" : "0FOPP90TFEE927859",
                          "owner" : {
                            "email" : "victim.one@example.com",
                            "number" : "4156895423"
                          }
                        }
                      },
                      "problem_details" : {
                        "type" : "string"
                      },
                      "status" : {
                        "type" : "string"
                      },
                      "created_on" : {
                        "type" : "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/workshop/api/mechanic/service_requests" : {
        "get" : {
          "operationId" : "get_service_requests_for_mechanic",
          "summary" : "Get Service Reports for a Mechanic",
          "description" : "Fetch all service requests assigned to this specific mechanic.",
          "tags" : [ "Workshop / Mechanic" ],
          "security" : [ {
            "bearerAuth" : [ ]
          } ],
          "responses" : {
            "200" : {
              "description" : "OK",
              "content" : {
                "application/json" : {
                  "schema" : {
                    "$ref" : "#/components/schemas/ServiceRequests"
                  }
                }
              }
            },
            "401" : {
              "description" : "Unauthorized",
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    },
                    "required" : [ "message" ]
                  }
                }
              }
            },
            "403" : {
              "description" : "Forbidden",
              "content" : {
                "application/json" : {
                  "schema" : {
                    "$ref" : "#/components/schemas/ServiceRequests"
                  }
                }
              }
            }
          }
        }
      },
      "/workshop/api/mechanic/signup" : {
        "post" : {
          "operationId" : "mechanic_signup",
          "summary" : "New Mechanic Signup",
          "description" : "Used to register a new mechanic in the workshop.",
          "tags" : [ "Workshop / Mechanic" ],
          "security" : [ ],
          "requestBody" : {
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "object",
                  "properties" : {
                    "name" : {
                      "type" : "string"
                    },
                    "email" : {
                      "type" : "string",
                      "format" : "email"
                    },
                    "number" : {
                      "type" : "string"
                    },
                    "password" : {
                      "type" : "string"
                    },
                    "mechanic_code" : {
                      "type" : "string"
                    }
                  },
                  "required" : [ "email", "mechanic_code", "name", "number", "password" ]
                }
              }
            },
            "required" : true
          },
          "responses" : {
            "200" : {
              "description" : "OK",
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    },
                    "example" : {
                      "message" : "Mechanic created with email: john@workshop.com"
                    }
                  }
                }
              }
            },
            "400" : {
              "content" : {
                "application/json" : {
                  "schema" : {
                    "type" : "object",
                    "required" : [ "message" ],
                    "properties" : {
                      "message" : {
                        "type" : "string"
                      }
                    },
                    "example" : {
                      "message" : "Mechanic code already exists!'"
                    }
                  }
                }
              },
              "description" : "Bad Request!"
            }
          }
        }
      }
    },
    "components" : {
        "schemas" : {
          "Order" : {
            "type" : "object",
            "properties" : {
              "id" : {
                "type" : "integer",
                "readOnly" : true
              },
              "user" : {
                "$ref" : "#/components/schemas/User"
              },
              "product" : {
                "$ref" : "#/components/schemas/Product"
              },
              "quantity" : {
                "type" : "integer"
              },
              "status" : {
                "$ref" : "#/components/schemas/OrderStatusEnum"
              },
              "created_on" : {
                "type" : "string",
                "format" : "date-time"
              }
            },
            "required" : [ "created_on", "id", "product", "user" ]
          },
          "User" : {
            "type" : "object",
            "properties" : {
              "email" : {
                "type" : "string"
              },
              "number" : {
                "type" : "string",
                "nullable" : true
              }
            },
            "required" : [ "email" ]
          },
          "NewProduct" : {
            "type" : "object",
            "properties" : {
              "name" : {
                "type" : "string"
              },
              "price" : {
                "type" : "string",
                "format" : "decimal",
                "pattern" : "^\\d{0,18}(\\.\\d{0,2})?$"
              },
              "image_url" : {
                "type" : "string",
                "format" : "url"
              }
            },
            "required" : [ "image_url", "name", "price" ]
          },
          "Product" : {
            "type" : "object",
            "properties" : {
              "id" : {
                "type" : "integer",
                "readOnly" : true
              },
              "name" : {
                "type" : "string"
              },
              "price" : {
                "type" : "string",
                "format" : "decimal",
                "pattern" : "^\\d{0,18}(\\.\\d{0,2})?$"
              },
              "image_url" : {
                "type" : "string",
                "format" : "url"
              }
            },
            "required" : [ "id", "image_url", "name", "price" ]
          },
          "OrderStatusEnum" : {
            "enum" : [ "delivered", "return pending", "returned" ],
            "type" : "string"
          },
          "ProductQuantity" : {
            "type" : "object",
            "properties" : {
              "product_id" : {
                "type" : "integer",
                "example": 1
              },
              "quantity" : {
                "type" : "integer",
                "example": 1
              }
            },
            "required" : [ "product_id", "quantity" ]
          },
          "Post" : {
            "title" : "Post",
            "required" : [ "id", "title", "content", "author", "comments", "authorid", "CreatedAt" ],
            "type" : "object",
            "properties" : {
              "id" : {
                "type" : "string"
              },
              "title" : {
                "type" : "string"
              },
              "content" : {
                "type" : "string"
              },
              "author" : {
                "$ref" : "#/components/schemas/Author"
              },
              "comments" : {
                "type" : "array",
                "items" : {
                  "type" : "string"
                },
                "description" : ""
              },
              "authorid" : {
                "type" : "integer",
                "format" : "int32"
              },
              "CreatedAt" : {
                "type" : "string"
              }
            },
            "example" : {
              "id" : "ConZLXacq3MqhbLQDrbNLf",
              "title" : "Title 3",
              "content" : "Hello world 3",
              "author" : {
                "nickname" : "Hacker",
                "email" : "hacker@darkweb.com",
                "vehicleid" : "abac4018-5a38-466c-ab7f-361908afeab6",
                "profile_pic_url" : "",
                "created_at" : "2021-09-16T01:46:32.432Z"
              },
              "comments" : [ ],
              "authorid" : 3,
              "CreatedAt" : "2021-09-16T01:46:32.432Z"
            }
          },
          "Author" : {
            "title" : "Author",
            "required" : [ "nickname", "email", "vehicleid", "profile_pic_url", "created_at" ],
            "type" : "object",
            "properties" : {
              "nickname" : {
                "type" : "string"
              },
              "email" : {
                "type" : "string"
              },
              "vehicleid" : {
                "type" : "string"
              },
              "profile_pic_url" : {
                "type" : "string"
              },
              "created_at" : {
                "type" : "string"
              }
            },
            "example" : {
              "nickname" : "Hacker",
              "email" : "hacker@darkweb.com",
              "vehicleid" : "abac4018-5a38-466c-ab7f-361908afeab6",
              "profile_pic_url" : "",
              "created_at" : "2021-09-16T01:46:32.432Z"
            }
          },
          "VideoForm" : {
            "type" : "object",
            "properties" : {
              "id" : {
                "type" : "integer",
                "format" : "int64"
              },
              "videoName" : {
                "type" : "string"
              },
              "video_url" : {
                "type" : "string"
              },
              "conversion_params" : {
                "type" : "string"
              }
            }
          },
          "CRAPIResponse" : {
            "type" : "object",
            "properties" : {
              "message" : {
                "type" : "string"
              },
              "status" : {
                "type" : "integer",
                "format" : "int32"
              }
            }
          },
          "OtpForm" : {
            "required" : [ "email", "otp", "password" ],
            "type" : "object",
            "properties" : {
              "otp" : {
                "maxLength" : 4,
                "minLength" : 3,
                "type" : "string",
                "example": "9969"
              },
              "password" : {
                "maxLength" : 30,
                "minLength" : 5,
                "type" : "string",
                "example": "5hmb0gvyC__hVQg"
              },
              "email" : {
                "maxLength" : 30,
                "minLength" : 5,
                "type" : "string",
                "example": "Cristobal.Weissnat@example.com"   
              }
            }
          },
          "JwtResponse" : {
            "type" : "object",
            "properties" : {
              "token" : {
                "type" : "string"
              },
              "type" : {
                "type" : "string"
              },
              "message" : {
                "type" : "string"
              },
              "role" : {
                "type" : "string",
                "enum" : [ "ROLE_UNDEFINED", "ROLE_USER", "ROLE_MECHANIC", "ROLE_ADMIN" ]
              }
            }
          },
          "LoginWithEmailToken" : {
            "required" : [ "email", "token" ],
            "type" : "object",
            "properties" : {
              "email" : {
                "maxLength" : 60,
                "minLength" : 3,
                "type" : "string"
              },
              "token" : {
                "maxLength" : 60,
                "minLength" : 3,
                "type" : "string"
              }
            }
          },
          "ProfileVideo" : {
            "type" : "object",
            "required" : [ "id", "video_name", "converstion_params", "video", "user" ],
            "properties" : {
              "id" : {
                "type" : "number"
              },
              "video_name" : {
                "type" : "string"
              },
              "conversion_params" : {
                "type" : "string"
              },
              "video" : {
                "type" : "string"
              },
              "user" : {
                "$ref" : "#/components/schemas/User"
              }
            }
          },
          "Coupon" : {
            "type" : "object",
            "properties" : {
              "amount" : {
                "type" : "string"
              },
              "coupon_code" : {
                "type" : "string"
              },
              "createdAt" : {
                "type" : "string"
              }
            },
            "required" : [ "amount", "coupon_code" ]
          },
          "ServiceRequests" : {
            "title" : "Service Requests",
            "type" : "object",
            "required" : [ "service_requests" ],
            "properties" : {
              "service_requests" : {
                "type" : "array",
                "items" : {
                  "type" : "object",
                  "required" : [ "created_on", "id", "mechanic", "vehicle" ],
                  "properties" : {
                    "id" : {
                      "type" : "integer",
                      "readOnly" : true
                    },
                    "mechanic" : {
                      "type" : "object",
                      "required" : [ "id", "mechanic_code", "user" ],
                      "properties" : {
                        "id" : {
                          "type" : "integer",
                          "readOnly" : true
                        },
                        "mechanic_code" : {
                          "type" : "string"
                        },
                        "user" : {
                          "type" : "object",
                          "required" : [ "email" ],
                          "properties" : {
                            "email" : {
                              "type" : "string"
                            },
                            "number" : {
                              "type" : "string",
                              "nullable" : true
                            }
                          }
                        }
                      }
                    },
                    "vehicle" : {
                      "type" : "object",
                      "properties" : {
                        "id" : {
                          "type" : "integer",
                          "readOnly" : true
                        },
                        "vin" : {
                          "type" : "string"
                        },
                        "owner" : {
                          "type" : "object",
                          "properties" : {
                            "email" : {
                              "type" : "string"
                            },
                            "number" : {
                              "type" : "string",
                              "nullable" : true
                            }
                          },
                          "required" : [ "email" ]
                        }
                      },
                      "required" : [ "id", "owner", "vin" ]
                    },
                    "problem_details" : {
                      "type" : "string"
                    },
                    "status" : {
                      "enum" : [ "Pending", "Finished" ],
                      "type" : "string"
                    },
                    "created_on" : {
                      "type" : "string",
                      "format" : "date-time"
                    }
                  }
                }
              }
            }
          }
        },
        "securitySchemes" : {
          "bearerAuth" : {
            "type" : "http",
            "scheme" : "bearer",
            "bearerFormat" : "JWT"
          }
        }
      }
}